// React hooks
import { useState } from 'react';

// nextjs components
import Head from 'next/head'

// MUI components - layout
import Container from '@mui/material/Container';

// MUI components - physical (header)
import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

// our own components
import ReviewCard from './components/ReviewCard';
import ReviewForm from './components/ReviewForm'


export default function Home() {

  const [reviews, setReviews] = useState([])

  return (
    <div>
      <Head>
        <title>Adaptation Reviews.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            Adaptations Reviews
          </Typography>
        </Toolbar>
      </AppBar>

      <main>
        <Container maxWidth="md">

          {/* Because I need to overwrite reviews in my form (upon submission),
              I need to pass the reviews (so I can read it) & its setter (so I can overwrite it)
              down into the form component.

              We're *sharing state* between this top-level page component & the form. 
          */}
          <ReviewForm
            reviews={reviews}
            onReviewsChange={setReviews}
          />

          {reviews.map((adaptation, index) => {
            return <ReviewCard
              key={index}
              rating={adaptation.rating}
              title={adaptation.title}
              comment={adaptation.comment}
            />
          })}

        </Container>
      </main>
    </div>
  )
}
